//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccidentVictim
    {
        public int AccidentVictimID { get; set; }
        public int AccidentID { get; set; }
        public int VictimID { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual Victim Victim { get; set; }
    }
}
