//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DTP_Entities : DbContext
    {
        private static DTP_Entities _context;
        public DTP_Entities()
            : base("name=DTP_Entities")
        {
        }

        public static DTP_Entities GetContext()
        {
            if(_context==null)
            {
                _context = new DTP_Entities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accident { get; set; }
        public virtual DbSet<AccidentVictim> AccidentVictim { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryLicense> CategoryLicense { get; set; }
        public virtual DbSet<DrivingLicense> DrivingLicense { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Victim> Victim { get; set; }
    }
}
