//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTP_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingLicense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrivingLicense()
        {
            this.CategoryLicense = new HashSet<CategoryLicense>();
            this.Victim = new HashSet<Victim>();
        }
    
        public int DrivingLicenseID { get; set; }
        public string DrivingLicenseNumber { get; set; }
        public System.DateTime DateOfAcquisition { get; set; }
        public System.DateTime DateOfExpiration { get; set; }
        public string GIBDDCode { get; set; }
        public string Photo { get; set; }
        public string PlaceOfResidence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryLicense> CategoryLicense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Victim> Victim { get; set; }
    }
}
